name: Maven tests

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up JDK 21
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven

      - name: Run Maven tests
        run: |
          mvn clean install -DskipTests
          modules=("dubbo-common" 
                  "dubbo-serialization/dubbo-serialization-hessian2" 
                  "dubbo-serialization/dubbo-serialization-fastjson2" 
                  "dubbo-remoting/dubbo-remoting-api" 
                  "dubbo-metrics/dubbo-metrics-api" 
                  "dubbo-config/dubbo-config-api")
                  
          for module in "${modules[@]}"; do
            echo "Running tests for $module"
            mvn -B verify -Pjacoco -f $module/pom.xml
          done

      - name: Get JaCoCo Coverage
        id: coverage
        run: |
          coverageA=$(python3 config/coverage.py target/site/dubbo-common/jacoco/jacoco.csv)
          echo "COVERAGEA=\"$coverageA\"" >> $GITHUB_ENV

      - name: Fail if coverage has not improved.
        run: |
          coverageA=$COVERAGEA
          threshold1=24.46

          if (( $(echo "$coverageA >= $threshold1" | bc -l) )); then
            echo "New coverage for module 1: $coverage%. Coverage has improved!"
            exit 1
          else
            echo "Coverage is still equal to $threshold1%. Please improve."
          fi
