name: Maven tests

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up JDK 21
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven

      - name: Run Maven tests
        run: |
          mvn clean install -DskipTests
          modules=("dubbo-common" 
                  "dubbo-serialization/dubbo-serialization-hessian2" 
                  "dubbo-serialization/dubbo-serialization-fastjson2" 
                  "dubbo-remoting/dubbo-remoting-api" 
                  "dubbo-metrics/dubbo-metrics-api" 
                  "dubbo-config/dubbo-config-api")
                  
          for module in "${modules[@]}"; do
            echo "Running tests for $module"
            mvn -B verify -Pjacoco -f $module/pom.xml
          done

      - name: Get JaCoCo Coverage
        id: COVERAGE
        run: |
          {
            echo 'Coverage1<<COVERAGE1'
            python3 config/coverage.py dubbo-common/target/site/jacoco/jacoco.csv
            echo COVERAGE1
          } >> "$GITHUB_ENV"
          {
            echo 'Coverage2<<COVERAGE2'
            python3 config/coverage.py dubbo-serialization/dubbo-serialization-hessian2/target/site/jacoco/jacoco.csv
            echo COVERAGE2
          } >> "$GITHUB_ENV"
          {
            echo 'Coverage3<<COVERAGE3'
            python3 config/coverage.py dubbo-serialization/dubbo-serialization-fastjson2/target/site/jacoco/jacoco.csv
            echo COVERAGE3
          } >> "$GITHUB_ENV"
          {
            echo 'Coverage4<<COVERAGE4'
            python3 config/coverage.py dubbo-remoting/dubbo-remoting-api/target/site/jacoco/jacoco.csv
            echo COVERAGE4
          } >> "$GITHUB_ENV"
          {
            echo 'Coverage5<<COVERAGE5'
            python3 config/coverage.py dubbo-metrics/dubbo-metrics-api/target/site/jacoco/jacoco.csv
            echo COVERAGE5
          } >> "$GITHUB_ENV"
          {
            echo 'Coverage6<<COVERAGE6'
            python3 config/coverage.py dubbo-config/dubbo-config-api/target/site/jacoco/jacoco.csv
            echo COVERAGE6
          } >> "$GITHUB_ENV"

      - name: Fail if coverage has not improved.
        run: |
          threshold1=65.38
          threshold2=56.79
          threshold3=68.38
          threshold4=53.44
          threshold5=34.20
          threshold6=74.54

          if (( $(echo "$COVERAGE1 >= $threshold1" | bc -l) )); then
            echo -e "New coverage for the module dubbo-common - $COVERAGE1\%. Coverage is improved!"
          elif (( $(echo "$COVERAGE2 >= $threshold2" | bc -l) )); then
            echo -e "New coverage for the module dubbo-serialization-hessian2 - $COVERAGE2\%. Coverage is improved!"
          elif (( $(echo "$COVERAGE3 >= $threshold3" | bc -l) )); then
            echo -e "New coverage for module dubbo-serialization-fastjson2 - $COVERAGE3\%. Coverage is improved!"
          elif (( $(echo "$COVERAGE4 >= $threshold4" | bc -l) )); then
            echo -e "New coverage for module dubbo-remoting-api - $COVERAGE4\%. Coverage is improved!"
          elif (( $(echo "$COVERAGE5 >= $threshold5" | bc -l) )); then
            echo -e "New coverage for module dubbo-metrics-api - $COVERAGE5\%. Coverage is improved!"
          elif (( $(echo "$COVERAGE6 >= $threshold6" | bc -l) )); then
            echo -e "New coverage for module dubbo-config-api - $COVERAGE6\%. Coverage is improved!"
          else
            echo "Coverage is not improved."
            exit 1
          fi
