name: Maven tests

on:
  pull_request:
    branches:
      - '3.2'
  push:
    branches:
      - '3.2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up JDK 21
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven
      - name: Run Maven tests
        run: >
          mvn -B verify -Pjacoco
          jacoco:report
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'commit badge'
          add: '*.svg'
